strategy_name = "EMACrossoverRSI"

[[indicators]]
name = "ema_fast"
type = "EMA"
parameters = { period = 10, source = "mid_price" }

[[indicators]]
name = "ema_slow"
type = "EMA"
parameters = { period = 30, source = "mid_price" }

[[indicators]]
name = "rsi"
type = "RSI"
parameters = { period = 14, source = "mid_price" }

[[signals]]
name = "ema_cross_above"
type = "CrossesAbove"
indicator_a = "ema_fast"
indicator_b = "ema_slow"
cooldown = 10

[[signals]]
name = "ema_cross_below"
type = "CrossesBelow"
indicator_a = "ema_fast"
indicator_b = "ema_slow"
cooldown = 10

[[signals]]
name = "rsi_oversold"
type = "BelowValue"
indicator = "rsi"
value = 40

[[signals]]
name = "rsi_overbought"
type = "AboveValue"
indicator = "rsi"
value = 50

# If (positions == 0) AND (ema_cross_above AND rsi_oversold)
[[rules]]
type = "IF"
condition = "if_flat"
rule = { type = "AND", signals = ["ema_cross_above", "rsi_oversold"], action = "BUY", quantity = 1 }

# If (positions > 0) AND (ema_cross_below AND rsi_overbought)
[[rules]]
type = "IF"
condition = "if_long"
rule = { type = "AND", signals = ["ema_cross_below", "rsi_overbought"], action = "SELL", quantity = 1 }